version: '2'
services:
  applicationtma-app:
    image: applicationtma
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://applicationtma-postgresql:5432/ApplicationTMA
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8070:8070
  applicationtma-postgresql:
    extends:
      file: postgresql.yml
      service: applicationtma-postgresql
